name: 'Release Lookup'
description: 'Release Lookup Action'
author: 'Rojan Gh.'
inputs:
  token:
    required: true
    description: Token
  stage:
    required: true
    description: Target stage
  artifact_name:
    required: false
    description: Release Startup Action artifact name
    default: release-startup-outputs
  exports:
    required: false
    description: Export outputs as environment veriables
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
