name: Auto Merge

on:
  pull_request:
    types: [labeled]

jobs:
  merge:
    if: ${{ github.event.label.name == 'dependencies' }}
    uses: NoorDigitalAgency/.github/.github/workflows/auto-merge.yaml@main
    secrets:
      token: ${{ secrets.ACTIONS_TOKEN }}
