name: Auto Merge

on:
  workflow_run:
    workflows: ["Pre-Merge"]
    types: 
      - completed

jobs:
  merge:
    if: ${{ github.event.label.name == 'dependencies' }}
    uses: NoorDigitalAgency/.github/.github/workflows/auto-merge.yaml@main
    secrets:
      token: ${{ secrets.ACTIONS_TOKEN }}
