name: Publish

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to build and publish on
        default: develop
        type: choice
        options:
          - main
          - develop

jobs:
  publish:
    uses: NoorDigitalAgency/.github/.github/workflows/publish-github-action.yaml@main
    with:
      branch: ${{ github.event.inputs.branch }}
