name: Publish

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Auto Merge
    types:
      - completed

jobs:
  publish:
    uses: NoorDigitalAgency/.github/.github/workflows/publish-action.yaml@main
    with:
      branch: main
    secrets:
      token: ${{ secrets.ACTIONS_TOKEN }}
